import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import securityPlugin from 'eslint-plugin-security';

export default [
    js.configs.recommended,
    reactPlugin.configs.flat.recommended,
    reactHooksPlugin.configs.flat['recommended-latest'],
    {
        files: ['**/*.{ts,tsx}'],
        languageOptions: {
            parser: tsParser,
            parserOptions: {
                ecmaVersion: 2022,
                sourceType: 'module',
                ecmaFeatures: { jsx: true },
            },
            globals: {
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                location: 'readonly',
                history: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                console: 'readonly',
                fetch: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                Notification: 'readonly',
                performance: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                ResizeObserver: 'readonly',
                IntersectionObserver: 'readonly',
                MutationObserver: 'readonly',
                AbortController: 'readonly',
                FormData: 'readonly',
                Blob: 'readonly',
                FileReader: 'readonly',
                CustomEvent: 'readonly',
                Event: 'readonly',
                EventTarget: 'readonly',
                HTMLElement: 'readonly',
                HTMLInputElement: 'readonly',
                HTMLTextAreaElement: 'readonly',
                HTMLButtonElement: 'readonly',
                HTMLDivElement: 'readonly',
                HTMLAnchorElement: 'readonly',
                HTMLImageElement: 'readonly',
                HTMLCanvasElement: 'readonly',
                HTMLVideoElement: 'readonly',
                HTMLFormElement: 'readonly',
                HTMLSelectElement: 'readonly',
                Element: 'readonly',
                Node: 'readonly',
                MessageEvent: 'readonly',
                KeyboardEvent: 'readonly',
                MouseEvent: 'readonly',
                TouchEvent: 'readonly',
                PointerEvent: 'readonly',
                InputEvent: 'readonly',
                FocusEvent: 'readonly',
                DragEvent: 'readonly',
                WheelEvent: 'readonly',
                ClipboardEvent: 'readonly',
                GeolocationPosition: 'readonly',
                GeolocationPositionError: 'readonly',
                ServiceWorker: 'readonly',
                ServiceWorkerRegistration: 'readonly',
                ServiceWorkerContainer: 'readonly',
                Cache: 'readonly',
                CacheStorage: 'readonly',
                IDBDatabase: 'readonly',
                crypto: 'readonly',
                StorageEvent: 'readonly',
                google: 'readonly',
                confirm: 'readonly',
                alert: 'readonly',
                prompt: 'readonly',
                indexedDB: 'readonly',
                caches: 'readonly',
                self: 'readonly',
                globalThis: 'readonly',
                process: 'readonly',
                queueMicrotask: 'readonly',
                structuredClone: 'readonly',
                TextEncoder: 'readonly',
                TextDecoder: 'readonly',
            },
        },
        plugins: {
            '@typescript-eslint': tsPlugin,
            security: securityPlugin,
        },
        rules: {
            ...tsPlugin.configs.recommended.rules,
            'no-console': 'warn',
            'react-hooks/rules-of-hooks': 'error',
            'react-hooks/exhaustive-deps': 'warn',
            'react/react-in-jsx-scope': 'off',
            '@typescript-eslint/no-explicit-any': 'warn',
            '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
            // React Compiler rules (excesivamente estrictas para React 18 — apagadas)
            'react-hooks/react-compiler': 'off',
            // Reglas de seguridad críticas (error) y de advertencia (warn)
            'security/detect-eval-with-expression': 'error',
            'security/detect-non-literal-regexp': 'warn',
            'security/detect-non-literal-require': 'warn',
            'security/detect-object-injection': 'warn',
            'security/detect-possible-timing-attacks': 'warn',
            'security/detect-unsafe-regex': 'error',
        },
        settings: {
            react: { version: 'detect' },
        },
    },
    {
        ignores: ['node_modules/', 'dist/', 'functions/', 'vite.config.ts', 'vitest.config.ts', 'tailwind.config.js', 'postcss.config.js'],
    },
];
