/**
 * Espejo de solo lectura de functions/orderState.js — usar solo para reflejar
 * estados válidos en la UI (timeline, badges). La autoridad es el backend.
 */
export const ORDER_STATUS = {
  PENDING: "PENDING",
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PAID: "PAID",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  ACCEPTED: "ACCEPTED",
  IN_PREPARATION: "IN_PREPARATION",
  READY: "READY",
  AWAITING_DRIVER: "AWAITING_DRIVER",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  DISPUTED: "DISPUTED",
  REFUNDED: "REFUNDED",
};

export const STATUS_LABELS = {
  [ORDER_STATUS.PENDING]: "Pendiente",
  [ORDER_STATUS.PENDING_PAYMENT]: "Pendiente de pago",
  [ORDER_STATUS.PAID]: "Pagado",
  [ORDER_STATUS.PAYMENT_CONFIRMED]: "Pago confirmado",
  [ORDER_STATUS.ACCEPTED]: "Aceptado",
  [ORDER_STATUS.IN_PREPARATION]: "En preparación",
  [ORDER_STATUS.READY]: "Listo",
  [ORDER_STATUS.AWAITING_DRIVER]: "Esperando repartidor",
  [ORDER_STATUS.IN_TRANSIT]: "En camino",
  [ORDER_STATUS.DELIVERED]: "Entregado",
  [ORDER_STATUS.COMPLETED]: "Completado",
  [ORDER_STATUS.CANCELLED]: "Cancelado",
  [ORDER_STATUS.DISPUTED]: "Disputado",
  [ORDER_STATUS.REFUNDED]: "Reembolsado",
};

export const HAPPY_PATH = [
  ORDER_STATUS.PENDING,
  ORDER_STATUS.PAID,
  ORDER_STATUS.ACCEPTED,
  ORDER_STATUS.IN_PREPARATION,
  ORDER_STATUS.READY,
  ORDER_STATUS.IN_TRANSIT,
  ORDER_STATUS.DELIVERED,
  ORDER_STATUS.COMPLETED,
];

export function canTransition(from, to) {
  if (from === to) return false;
  return !!ALLOWED_TRANSITIONS[from]?.includes(to);
}

export const ALLOWED_TRANSITIONS = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.PAID, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PENDING_PAYMENT]: [ORDER_STATUS.PAYMENT_CONFIRMED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PAID]: [ORDER_STATUS.ACCEPTED, ORDER_STATUS.CANCELLED, ORDER_STATUS.REFUNDED, ORDER_STATUS.DISPUTED],
  [ORDER_STATUS.PAYMENT_CONFIRMED]: [ORDER_STATUS.ACCEPTED, ORDER_STATUS.CANCELLED, ORDER_STATUS.REFUNDED, ORDER_STATUS.DISPUTED],
  [ORDER_STATUS.ACCEPTED]: [ORDER_STATUS.IN_PREPARATION, ORDER_STATUS.READY, ORDER_STATUS.CANCELLED, ORDER_STATUS.DISPUTED],
  [ORDER_STATUS.IN_PREPARATION]: [ORDER_STATUS.READY, ORDER_STATUS.CANCELLED, ORDER_STATUS.DISPUTED],
  [ORDER_STATUS.READY]: [ORDER_STATUS.AWAITING_DRIVER, ORDER_STATUS.IN_TRANSIT, ORDER_STATUS.COMPLETED, ORDER_STATUS.CANCELLED, ORDER_STATUS.DISPUTED],
  [ORDER_STATUS.AWAITING_DRIVER]: [ORDER_STATUS.IN_TRANSIT, ORDER_STATUS.CANCELLED, ORDER_STATUS.DISPUTED],
  [ORDER_STATUS.IN_TRANSIT]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.DISPUTED],
  [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.COMPLETED, ORDER_STATUS.DISPUTED],
  [ORDER_STATUS.COMPLETED]: [ORDER_STATUS.DISPUTED, ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.CANCELLED]: [],
  [ORDER_STATUS.DISPUTED]: [ORDER_STATUS.REFUNDED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.REFUNDED]: [],
};
